# Generated by Django 3.1.4 on 2020-12-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCNN', '0002_auto_20201212_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='ImagenPredict',
        ),
    ]
